# Generated by Django 3.2.3 on 2021-05-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
